# Generated by Django 6.0 on 2026-01-03 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursosrealizados',
            name='rutacertificado',
            field=models.FileField(blank=True, null=True, upload_to='certificados/'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='rutacertificado',
            field=models.FileField(blank=True, null=True, upload_to='certificados/'),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='rutacertificado',
            field=models.FileField(blank=True, null=True, upload_to='certificados/'),
        ),
    ]
