# Generated by Django 6.0 on 2026-01-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_usuario', '0002_alter_cursosrealizados_rutacertificado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursosrealizados',
            name='descripcioncurso',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='descripcionperfil',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='descripcionfunciones',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='productosacademicos',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='productoslaborales',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='descripcionreconocimiento',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
