# Generated by Django 6.0 on 2026-01-06 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_usuario', '0003_alter_cursosrealizados_descripcioncurso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='imagenperfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='totalhoras',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
