# Generated by Django 6.0 on 2026-01-10 01:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_usuario', '0004_datospersonales_imagenperfil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursosrealizados',
            name='rutacertificado',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='rutacertificado'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='imagenperfil',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagenperfil'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='rutacertificado',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='rutacertificado'),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='rutacertificado',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='rutacertificado'),
        ),
    ]
